### ISSUE TITLE
implementing PAiNN

### ISSUE THREAD

**Issue by thegodone** [aimat-lab/gcnn_keras#14]
Unfortunately their code is not available, but it's close to “SchNet" - "GVP-GNN" - "Dimenet":

Can you implement it ? 

https://arxiv.org/pdf/2102.03150.pdf

If I understand the paper, this is like this :   

S = linear(384,(SiLU(linear(128,Sj))))
W = fcut(linear(384,RBF(20,Rij)))
SR = GVP(S,W) => Split into (3)
Vim = Sum(Vj*SR[0]+SR[2]*Rij/L2(Rij))i
DSim = Sum(SR[1])i 

![image](https://user-images.githubusercontent.com/1186658/123555527-9fb59880-d786-11eb-8c9c-a6e433613f6c.png)

**Comment by PatReis** [comment]
Yeah, this looks very intersting. I will tray to add it but it make take a little time.

**Comment by thegodone** [comment]
Can you test on Lipo Dataset too ?

**Comment by PatReis** [comment]
Hey, I have added also an example for Lipop dataset and it works also nicely: something like 0.38. However, PAiNN is more of a geometric molecule net. So I used the initial geometry guess of rdkit for the coordinates and passed it to the model. I trained on QM9 LUMO and got this result, which is quite good
![painn_loss](https://user-images.githubusercontent.com/64005383/126962016-11f5ba6c-6c54-4bcd-815c-0434d9a204ea.png)

**Comment by PatReis** [comment]
However, I did not fully figure out what they mean with the cos-cutoff. It does not really make sense to me since it is on the linear combinations of radial basis encoding. They do not clearly say in the paper if the use the actual cos-output or the initial distance and multiply with the filter or what the cutoff is supposed to be, since the linear combinations are always aroun 1 (provided proper weight initialization...).
