### ISSUE TITLE
attentiveFP "attention" 

### ISSUE THREAD

**Issue by thegodone** [aimat-lab/gcnn_keras#16]
I've just discovered that AttentiveFP PyG code uses "Gat version" of attention while in original code they use "Gatv2 version" strategy. Can you check which one you implement in your code please ?

![image](https://user-images.githubusercontent.com/1186658/123933060-4e79f480-d992-11eb-8211-12dd8d43175f.png)

page 5 from here https://arxiv.org/pdf/2105.14491.pdf

I guess your implementation is not correct:

![image](https://user-images.githubusercontent.com/1186658/123934200-55edcd80-d993-11eb-9e07-0eca6ccffe73.png)

![image](https://user-images.githubusercontent.com/1186658/123936368-67d07000-d995-11eb-9cb4-bd17fec16125.png)

do you add a bias in the dense ?
![image](https://user-images.githubusercontent.com/1186658/123934355-7e75c780-d993-11eb-9bb8-2d862fc16c8c.png)

**Comment by thegodone** [comment]
I have around 0.55 rmse on lipop now in the paper it's 0.57 (not same split of course) with your last code PERFECT!

**Comment by thegodone** [comment]
would it be possible to add GATv2 too in the litterature model https://arxiv.org/pdf/2105.14491.pdf ?

**Comment by thegodone** [comment]
![image](https://user-images.githubusercontent.com/1186658/123961058-416bfe00-d9b0-11eb-9cd2-cf432350090f.png)

get also same on lipop run interesting...

**Comment by PatReis** [comment]
Okay, I have added also an AttentionHeadGATV2 class with the difference you mentioned. But I am confused that in AttentiveFP they write:
![grafik](https://user-images.githubusercontent.com/64005383/123971575-78dfa800-d9ba-11eb-9f7e-9e5af2b73866.png)
which would mean that the attention weights are not a scalar per edge but like a vector per edge since they miss the :math:'a^T' as in GAT. I try to find out in their implementation...

**Comment by PatReis** [comment]
That is strange. I have run it multiple times now and never had that. Is it every time?

**Comment by thegodone** [comment]
No it’s happens once only 

Envoyé de mon iPhone
