### ISSUE TITLE
how to use Balloon instead of RDKit to generate conformer ?

### ISSUE THREAD

**Issue by thegodone** [aimat-lab/gcnn_keras#31]
For very complex molecules RDKit can return an error to generate 3D molecule conformer: there is a tool free that may help to solve this issue
http://users.abo.fi/mivainio/balloon/
Is it possible to find a way for very complex molecules to take into account this issue

**Comment by PatReis** [comment]
Yes, this is a great idea. I was having the same issue. I will try to make a conformer workflow including openbabel and ballon with some fallbacks. I will also try to make it paralllel.
However, I will likely want to stay with RDKit for the molecular properties, since otherwise it will be tricky to make the same properties across backends since they likely use different algorithms and could confuse the NN.
So if RDKit does not accept the smile at all, I don't really know what to do.
But the conformers can be treated separately.

**Comment by thegodone** [comment]
I would simply propose first two possibilities as an option:
- RDKit only for molecule and 3D conformer generation (as is)
- RDkit for molecule read & save into a sdf file + balloon to generate the 3D conformer
